[package]
name = "pbgui-style-engine"
version = "0.1.0"
authors = ["jlgerber <jlgerber@gmail.com>"]
edition = "2018"

[dependencies]
handlebars = "2.0.4"
serde_json = "1.0.44"
serde = "1.0.104"
serde_derive = "1.0.104"
rust-hsluv = "0.1.3"
